2024-07-05 18:53:59,224 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Configure stats pid to 22033
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Loading settings from /home/gaston/.config/wandb/settings
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Loading settings from /media/gaston/gaston1/DEV/ACTIA/workstation/scripts/wandb/settings
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***', 'root_dir': '/media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet', 'silent': 'true'}
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'workstation/scripts/train.py', 'program_abspath': '/media/gaston/gaston1/DEV/ACTIA/workstation/scripts/train.py', 'program': '/media/gaston/gaston1/DEV/ACTIA/workstation/scripts/train.py'}
2024-07-05 18:53:59,225 INFO    MainThread:22033 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-05 18:53:59,226 INFO    MainThread:22033 [wandb_init.py:_log_setup():529] Logging user logs to /media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet/wandb/run-20240705_185359-lzuwbx9u/logs/debug.log
2024-07-05 18:53:59,226 INFO    MainThread:22033 [wandb_init.py:_log_setup():530] Logging internal logs to /media/gaston/gaston1/DEV/ACTIA/workstation/logs/Teachers/Unet/wandb/run-20240705_185359-lzuwbx9u/logs/debug-internal.log
2024-07-05 18:53:59,227 INFO    MainThread:22033 [wandb_init.py:init():569] calling init triggers
2024-07-05 18:53:59,227 INFO    MainThread:22033 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-05 18:53:59,227 INFO    MainThread:22033 [wandb_init.py:init():619] starting backend
2024-07-05 18:53:59,227 INFO    MainThread:22033 [wandb_init.py:init():623] setting up manager
2024-07-05 18:53:59,235 INFO    MainThread:22033 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-05 18:53:59,237 INFO    MainThread:22033 [wandb_init.py:init():631] backend started and connected
2024-07-05 18:53:59,249 INFO    MainThread:22033 [wandb_init.py:init():720] updated telemetry
2024-07-05 18:53:59,268 INFO    MainThread:22033 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-05 18:54:00,114 INFO    MainThread:22033 [wandb_run.py:_on_init():2402] communicating current version
2024-07-05 18:54:00,362 INFO    MainThread:22033 [wandb_run.py:_on_init():2411] got version response 
2024-07-05 18:54:00,363 INFO    MainThread:22033 [wandb_init.py:init():804] starting run threads in backend
2024-07-05 18:54:00,766 INFO    MainThread:22033 [wandb_run.py:_console_start():2380] atexit reg
2024-07-05 18:54:00,767 INFO    MainThread:22033 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2024-07-05 18:54:00,768 INFO    MainThread:22033 [wandb_run.py:_redirect():2300] Wrapping output streams.
2024-07-05 18:54:00,768 INFO    MainThread:22033 [wandb_run.py:_redirect():2325] Redirects installed.
2024-07-05 18:54:00,771 INFO    MainThread:22033 [wandb_init.py:init():847] run started, returning control to user process
2024-07-05 18:54:00,771 INFO    MainThread:22033 [wandb_run.py:_config_callback():1382] config_cb None None {'batch_size': 4, 'lr': 0.0003, 'epochs': 4, 'step_size': 10, 'gamma': 0.5}
2024-07-05 19:01:01,880 INFO    MainThread:22033 [wandb_run.py:_finish():2109] finishing run https-www-supcom-tn-/my_project/lzuwbx9u
2024-07-05 19:01:01,909 INFO    MainThread:22033 [wandb_run.py:_atexit_cleanup():2349] got exitcode: 0
2024-07-05 19:01:01,928 INFO    MainThread:22033 [wandb_run.py:_restore():2332] restore
2024-07-05 19:01:01,931 INFO    MainThread:22033 [wandb_run.py:_restore():2338] restore done
